alias ll='ls -lh'

cdl() {
  cd "$1"
  ls -lh
}

# navigation
alias l='exa --long --group --group-directories-first'
alias la='exa -la --group --group-directories-first'
alias vi='nvim'
alias rn='ranger'
alias jj='nvim ~/crypt/journal/journal.lft'
alias jt='nvim ~/crypt/journal/journal-tech.lft'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# directories
alias gb='cd ~/bin'
alias gc='cd ~/.config'
alias gd='cd ~/dotfiles'
alias gh='cd ~/sites/hugle.uk'
alias gk='cd ~/sites/carrollonline.uk/club38.carrollonline.uk'
alias gn='cd ~/.config/nvim'
alias gp='cd ~/.local/share/nvim/site/pack/packer/start/'
alias gP='cd ~/code/nvim-plugins-hc'
alias gz='cd ~/sites/chanadmin'

# commands
alias ssc='sudo systemctl'
alias sjc='sudo journalctl'

# programs
alias brave="brave-beta"
