#!/bin/sh

CONFIGDIR=$HOME/.config
SOURCEDIR=$HOME/dotfiles

link() {
	DIR=$CONFIGDIR/$1
	
	if [ -d $DIR ]; then
		mv $DIR $DIR.bk
	fi

	ln -s $SOURCEDIR/common/$1 $DIR
}

declare -a configs=(
	"btop"
	"foot"
	"redshift"
	"rofi"
	"waybar"
)

for val in "${configs[@]}"	
do
	link $val
done

ln -s $SOURCEDIR/sway $CONFIGDIR/sway
