#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# HC
eval $(ssh-agent)

# uk keymap
setxkbmap gb &

# compositor
picom -f &

# wallpaper
xwallpaper --maximize $HOME/.config/wallpaper.png &

#exec i3
#exec dwm 

while true; do
		dwmblocks
    	sleep 2
done &

while true; do
	dwm >/dev/null
	# to log stderrors to a file
	# dwm 2> ~/Build/dwm/dwm.log
done
