#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# HC
eval $(ssh-agent)
#exec i3

# uk keymap
setxkbmap gb &

# compositor
picom -f &

# hot start dwm
#while true; do
#    dwm >/dev/null 2>&1
#done

# wallpaper
xwallpaper --maximize $HOME/.config/wallpaper.png &

# dwm status bar
#dwmstatus 2>&1 >/dev/null & 
#/home/hughie/tools/dwn-bar/dwm_bar.sh &

#exec dwm
exec i3
