[env]
TERM = "alacritty"

[font]
size = 11
normal = { family = "JetBrains Mono", style = "regular" }

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
opacity = 0.9

[window.padding]
x = 4
y = 4
