# ~/.profile

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export VISUAL=nvim;
export EDITOR=nvim
export TERMINAL=foot
export BROWSER=brave-beta
export RANGER_LOAD_DEFAULT_RC=FALSE

# fuzzy finder
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden --color=always'
source /usr/share/fzf/completion.bash
source /usr/share/fzf/key-bindings.bash
#export FZF_DEFAULT_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/appimages"
export PATH="$PATH:$HOME/sites/chanadmin/public/vendor/bin"
export GEM_HOME="$HOME/.local/share/gem"
export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"

# gpg and ssh agents
GPG_TTY=$(tty)
export GPG_TTY
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# start the ssh-agent
SSH_ENV="$HOME/.ssh/agent-environment"

function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi

#xwallpaper --maximize $HOME/.config/wallpaper.png

# run the remaps script, switching caps/esc and more; check it for more info
# ~/.local/bin/remaps

source ~/.bashrc

