#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# uk keymap
#setxkbmap gb, shavian & halmak
setxkbmap -option 'grp:alt_space_toggle' -layout gb,halmak,shavian -variant sh21

# Decrease key repeat delay to 300ms and increase key repeat rate to 50 per second.
xset r rate 300 50

redshift &
picom -f &
gtk-application-prefer-dark-theme = true

exec i3
